# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @keywords internal
#' @noRd
multipleinversion <- function(A, rho, L, R, lambda2) {
    .Call('_ADMMadj5_multipleinversion', PACKAGE = 'ADMMadj5', A, rho, L, R, lambda2)
}

admm_tv <- function(b, xinit, lambda, reltol, abstol, maxiter, rho, alpha) {
    .Call('_ADMMadj5_admm_tv', PACKAGE = 'ADMMadj5', b, xinit, lambda, reltol, abstol, maxiter, rho, alpha)
}

admm_bp <- function(A, b, xinit, reltol, abstol, maxiter, rho, alpha) {
    .Call('_ADMMadj5_admm_bp', PACKAGE = 'ADMMadj5', A, b, xinit, reltol, abstol, maxiter, rho, alpha)
}

admm_enet <- function(A, b, lambda, alpha, reltol, abstol, maxiter, rho) {
    .Call('_ADMMadj5_admm_enet', PACKAGE = 'ADMMadj5', A, b, lambda, alpha, reltol, abstol, maxiter, rho)
}

admm_genlasso <- function(A, b, D, lambda, reltol, abstol, maxiter, rho) {
    .Call('_ADMMadj5_admm_genlasso', PACKAGE = 'ADMMadj5', A, b, D, lambda, reltol, abstol, maxiter, rho)
}

admm_lad <- function(A, b, xinit, reltol, abstol, maxiter, rho, alpha) {
    .Call('_ADMMadj5_admm_lad', PACKAGE = 'ADMMadj5', A, b, xinit, reltol, abstol, maxiter, rho, alpha)
}

admm_lasso <- function(A, b, lambda, xinit, reltol, abstol, maxiter, rho, alpha) {
    .Call('_ADMMadj5_admm_lasso', PACKAGE = 'ADMMadj5', A, b, lambda, xinit, reltol, abstol, maxiter, rho, alpha)
}

admm_rpca <- function(M, tol, maxiter, mu, lambda) {
    .Call('_ADMMadj5_admm_rpca', PACKAGE = 'ADMMadj5', M, tol, maxiter, mu, lambda)
}

admm_spca <- function(Sigma, reltol, abstol, maxiter, mu, rho) {
    .Call('_ADMMadj5_admm_spca', PACKAGE = 'ADMMadj5', Sigma, reltol, abstol, maxiter, mu, rho)
}

admm_sdp <- function(C, listA, b, mymu, myrho, mygamma, maxiter, abstol, printer) {
    .Call('_ADMMadj5_admm_sdp', PACKAGE = 'ADMMadj5', C, listA, b, mymu, myrho, mygamma, maxiter, abstol, printer)
}

